### ISSUE TITLE
Interesting ideas, any progress on an implementation?

### ISSUE THREAD

**Issue by aaronsgithub** [mbrochh/django-react-primer#1]
I came across this document and found it really interesting so I hope you don't mind me commenting here.

I am also trying to evaluate the potential of moving from a full Django stack to a Django backend + React front end with server side rendering.

Have you made any attempts at an implementation yet? 

I also noticed that you mentioned that django-cms was part of your old stack. Do you have any thoughts on how to include CMS features in the new stack?

**Comment by mbrochh** [comment]
@aaronsgithub thanks for bringing this repo back to my attention :)

I _have_ learned A LOT about react. We are now using it to build mobile apps with django-rest-framework as the API backend.

As part of the same project, we have to release a web frontend as well by the end of this month. When we have this baby online, I will finish this document with all the knowledge that I have acquired.

Stay tuned ;)

P.S.: RE: django-cms - we are in the process to eliminate django-cms from all our stacks. If I would still use it, I would probably create a reusable app that has django-cms as a dependency and provides API endpoints to get pages and placeholders and their contents etc.
