### ISSUE TITLE
Ok but..

### ISSUE THREAD

**Issue by alearcy** [mbrochh/django-react-primer#3]
...if you don't use anymore urls.py and view.py why do you continue to use Django? why don't you migrate to node.js and smaller solutions like Express or Hapi instead?
Thanks ;-)

**Comment by eddowh** [comment]
@alearcy - This is my person opinion, but..

Django is much more than `urls.py` and `views.py`. Its philosophy of "batteries included" with many other extended battery packs available allow you to quickly build things with minimum hassle. For one thing, does Express or Hapi have an ORM as nice as Django's? Also, Django's admin and management tool is so easy to use it's almost child's play.

I suggest you to check out https://docs.djangoproject.com/en/1.9/ref/contrib/; I don't know if Express or Hapi is even close to being as extensive as this - how do you even begin implementing stuff like geotagging and other cool stuff?

Anyways, Django is a great back-end for sophisticated development. Other than that though, I agree that Express or Hapi is suitable for what it's suited for - smaller and lighter applications that don't require very complex user management / you don't like ORMs.

**Comment by mbrochh** [comment]
Sorry for the late reply - Github's notification system is completely unusable for me and usually everything just gets lost in the noise.

@eddowh has answered very well, actually!
1. We still want to use the Django admin
2. We still want to be able to use Django's ORM
3. We want to use django-rest-framework for our API endpoints and this is probably the main reason why we will stick with Django for quite a while. DRF does a lot for us, be it authentication, permission handling, rate limiting/throttling, serialization of DB objects, automatic creation of a browsable and self-documenting API
